version: 0.0
os: linux
files:
  - source: codebuild/
    destination: /home/ec2-user/test/
  - source: scripts/
    destination: /home/ec2-user/scripts
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root

