version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - docker build -t minipunk .
  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Writing Dockerrun.aws.json file...
      - printf '{"AWSEBDockerrunVersion":"1","Ports":[{"ContainerPort":5000,"HostPort":80}]}' > Dockerrun.aws.json

artifacts:
  files:
    - Dockerrun.aws.json
    - .ebextensions/**/*
    - Dockerfile
